### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by aronlaszlo** [niklasf/pyson#2]
Dear Niklas,
I cannot run the hello_world program because I get the following errors:
aronlaszlo@aronlaszlo ~/Letöltések/pyson-master $ python -m pyson examples/hello_world.asl
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aronlaszlo/Letöltések/pyson-master/pyson/__main__.py", line 20, in <module>
    pyson.runtime.main(post_repl=False)
  File "pyson/runtime.py", line 846, in main
    import pyson.ext_stdlib
  File "pyson/ext_stdlib.py", line 3, in <module>
    import pyson.stdlib
  File "pyson/stdlib.py", line 32, in <module>
    import pyson.optimizer
  File "pyson/optimizer.py", line 666
    def __init__(self, *, preserve_errors=False):
                        ^
SyntaxError: invalid syntax
Could you help me please? (developing was fine, inside Python an import of pyson is ok)
Thanks
Laszlo

**Comment by suyjuris** [comment]
I could reproduce this issue, and issued a quick fix. Does it work on your end also?

**Comment by aronlaszlo** [comment]
Thank you! Sorry. I'm a novice: where can I find this quick fix?

**Comment by suyjuris** [comment]
The fix is committed (commit 0ada7c8) and updating your local copy of the repository via `git pull` (or your GUI of choice) should do the trick.

**Comment by aronlaszlo** [comment]
It works! It works! I love this project! Thank you very much, suyjuris! 
Best: Laszlo

**Comment by suyjuris** [comment]
You're welcome.
Best: Philipp
